export const DEMO_PERSONAS = [
  {
    id: "persona-telangana-mfg",
    name: "Rameshwar Rao",
    age: 34,
    gender: "Male",
    state: "Telangana",
    district: "Warangal",
    socialCategory: "SC",
    entrepreneurType: "EXISTING",
    businessName: "Rao Precision Metal Fabrication",
    businessType: "MANUFACTURING",
    industry: "Light Engineering & Fabrication",
    businessStage: "EARLY_STAGE",
    annualTurnover: 1200000, // 12 Lakhs
    employeeCount: 6,
    udyamRegistered: "YES",
    supportRequired: ["CAPITAL_SUBSIDY", "FINANCE_LOAN", "MACHINERY", "COLLATERAL_FREE"],
    targetAmount: 2500000,
    highlight: "SC Fabricator seeking T-PRIDE & PMEGP machinery subsidy",
    story: "Wants to purchase CNC plasma cutting machinery for agricultural equipment components."
  },
  {
    id: "persona-women-shg-artisan",
    name: "Ananya Devi",
    age: 29,
    gender: "Female",
    state: "Uttar Pradesh",
    district: "Varanasi",
    socialCategory: "OBC",
    entrepreneurType: "SHG_MEMBER",
    businessName: "Ganga Silk Weaver Self-Help Group",
    businessType: "HANDICRAFT_TEXTILE",
    industry: "Handloom & Textiles",
    businessStage: "GROWTH",
    annualTurnover: 450000, // 4.5 Lakhs
    employeeCount: 4,
    udyamRegistered: "APPLIED",
    supportRequired: ["WORKING_CAPITAL", "MARKETING_EXHIBITION", "SKILL_TRAINING", "COLLATERAL_FREE"],
    targetAmount: 300000,
    highlight: "Rural OBC Woman Artisan seeking MUDRA & Exhibition Subsidies",
    story: "Leading a 4-woman handloom cooperative looking for working capital and trade fair stalls on GeM."
  },
  {
    id: "persona-tribal-agritech",
    name: "Karan Birsa Munda",
    age: 26,
    gender: "Male",
    state: "Jharkhand",
    district: "Ranchi",
    socialCategory: "ST",
    entrepreneurType: "ASPIRING",
    businessName: "Birsa Herbal & Forest Honey Extracts",
    businessType: "AGRO_FOOD",
    industry: "Food Processing & Minor Forest Produce",
    businessStage: "IDEATION",
    annualTurnover: 0,
    employeeCount: 2,
    udyamRegistered: "NO",
    supportRequired: ["CAPITAL_SUBSIDY", "FINANCE_LOAN", "TECH_ADOPTION", "SKILL_TRAINING"],
    targetAmount: 1500000,
    highlight: "ST Youth launching Minor Forest Processing with PMFME & Stand-Up India",
    story: "First-generation tribal graduate planning an organic honey processing and packaging micro-facility."
  },
  {
    id: "persona-rural-woman-vendor",
    name: "Sunita Kumari",
    age: 41,
    gender: "Female",
    state: "Bihar",
    district: "Patna",
    socialCategory: "SC",
    entrepreneurType: "RURAL_WOMEN",
    businessName: "Sunita Spices & Home Essentials",
    businessType: "TRADING",
    industry: "Retail & Micro Spices Trading",
    businessStage: "EARLY_STAGE",
    annualTurnover: 220000,
    employeeCount: 1,
    udyamRegistered: "NO",
    supportRequired: ["WORKING_CAPITAL", "COLLATERAL_FREE", "FINANCE_LOAN"],
    targetAmount: 80000,
    highlight: "SC Woman Micro-Retailer seeking PM-SVANidhi & Mahila Samridhi",
    story: "Requires small working capital to expand bulk spice procurement with zero collateral."
  }
];
