export const DEMO_SCHEMES = [
  {
    id: "scheme-pmegp-001",
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    shortName: "PMEGP",
    department: "Ministry of Micro, Small and Medium Enterprises (MSME)",
    nodalAgency: "Khadi and Village Industries Commission (KVIC)",
    schemeType: "CAPITAL_SUBSIDY",
    typeLabel: "Credit Linked Capital Subsidy",
    description: "Credit linked subsidy scheme for setting up new micro-enterprises in manufacturing and services sectors. Special higher subsidy of up to 35% for marginalized categories including SC, ST, OBC, Women, Minorities, and PwD in rural areas.",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 50000000,
    maxProjectCost: 5000000, // 50 Lakhs for manufacturing, 20 Lakhs for services
    subsidyPercentSpecial: 35, // 35% rural special, 25% urban special
    subsidyPercentGeneral: 25, // 25% rural general, 15% urban general
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "PWD", "EWS", "GENERAL"],
    targetCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "PWD"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "AGRO_FOOD", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["Food Processing", "Textiles & Garments", "Light Engineering", "Wood & Bamboo", "Chemical & Herbal", "Services"],
    businessStages: ["IDEATION", "EARLY_STAGE"], // Strictly new units
    supportTypes: ["CAPITAL_SUBSIDY", "FINANCE_LOAN", "MACHINERY", "COLLATERAL_FREE"],
    benefits: [
      "Up to 35% subsidy on project cost in rural areas (25% in urban) for SC/ST/OBC/Women/Minorities/PwD",
      "Maximum project cost eligible: ₹50 Lakhs for Manufacturing & ₹20 Lakhs for Service sector",
      "Beneficiary own contribution only 5% for special categories (10% for General)",
      "Bank finance for remaining 60-70% of project cost with standard MSME interest rates",
      "No collateral security required for loans up to ₹10 Lakhs (covered under CGTMSE)"
    ],
    documents: [
      "Aadhaar Card",
      "PAN Card",
      "Caste / Community Certificate (for SC/ST/OBC/Minority/PwD claim)",
      "Rural Area Certificate / Gram Panchayat Certificate (if applying for rural subsidy)",
      "Detailed Project Report (DPR)",
      "Educational Qualification Certificate (8th pass certificate if project > ₹10L manufacturing / ₹5L service)",
      "Passport Size Photographs",
      "Bank Account Details / Cancelled Cheque",
      "EDP (Entrepreneurship Development Programme) Training Certificate (can be done post-approval)"
    ],
    applicationUrl: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
    officialWebsite: "https://msme.gov.in/pmegp",
    deadline: "Open All Year (Ongoing Budget Scheme)",
    applicationMode: "Online via KVIC PMEGP Portal followed by District Task Force Committee (DTFC) review",
    isActive: true,
    isPopular: true,
    badge: "Most Popular Subsidy"
  },
  {
    id: "scheme-standup-002",
    name: "Stand-Up India Scheme",
    shortName: "Stand-Up India",
    department: "Department of Financial Services, Ministry of Finance",
    nodalAgency: "Small Industries Development Bank of India (SIDBI)",
    schemeType: "BANK_LOAN",
    typeLabel: "Composite Loan (Term Loan + Working Capital)",
    description: "Facilitates bank loans between ₹10 Lakhs and ₹1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one Woman borrower per bank branch for setting up a greenfield enterprise.",
    minAge: 18,
    maxAge: 65,
    minTurnover: 0,
    maxTurnover: 100000000,
    maxProjectCost: 10000000, // 1 Crore
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "WOMEN"],
    targetCategories: ["SC", "ST", "WOMEN"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "TRADING", "AGRO_FOOD", "GREEN_TECH"],
    eligibleIndustries: ["Manufacturing", "Services", "Trading", "Agro-Allied Services", "Renewable Energy"],
    businessStages: ["IDEATION", "EARLY_STAGE"], // Greenfield only
    supportTypes: ["FINANCE_LOAN", "WORKING_CAPITAL", "MACHINERY", "COLLATERAL_FREE"],
    benefits: [
      "Composite loan between ₹10 Lakhs and ₹1 Crore covering up to 85% of total project cost",
      "Borrower margin money requirement only 15% (can be supplemented by state convergence schemes)",
      "Repayment period of up to 7 years with a maximum moratorium period of 18 months",
      "Working capital up to ₹10 Lakhs sanctioned by way of overdraft / RuPay debit card",
      "Credit guarantee cover available under Credit Guarantee Scheme for Stand-Up India (CGSUI)"
    ],
    documents: [
      "Aadhaar Card and PAN Card",
      "Proof of SC/ST Category Certificate (for SC/ST borrowers) or proof of Woman-owned majority shareholding (51%+)",
      "Greenfield Enterprise Declaration (First-time venture in sector)",
      "Detailed Project Report (DPR) with cash flow projections",
      "Rent Agreement / Proof of Business Premises",
      "Quotation for machinery / capital equipment",
      "Last 6 months Bank Statements"
    ],
    applicationUrl: "https://www.standupmitra.in/",
    officialWebsite: "https://www.standupmitra.in/",
    deadline: "Extended up to 2025-2026",
    applicationMode: "Directly at Bank Branch or via Stand-Up Mitra Portal",
    isActive: true,
    isPopular: true,
    badge: "Flagship SC/ST/Women"
  },
  {
    id: "scheme-mudra-003",
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    shortName: "MUDRA Loan",
    department: "Department of Financial Services, Ministry of Finance",
    nodalAgency: "MUDRA Ltd / Commercial & Regional Rural Banks",
    schemeType: "COLLATERAL_FREE_LOAN",
    typeLabel: "Micro Business Loan (Shishu, Kishore, Tarun)",
    description: "Provides collateral-free institutional credit up to ₹20 Lakhs (expanded under latest MSME guidelines) to micro and small non-farm enterprises for income generating activities in manufacturing, processing, trading, and services.",
    minAge: 18,
    maxAge: 65,
    minTurnover: 0,
    maxTurnover: 20000000,
    maxProjectCost: 2000000, // Up to 20 Lakhs
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "GENERAL", "EWS", "PWD"],
    targetCategories: ["OBC", "SC", "ST", "WOMEN", "GENERAL"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "TRADING", "AGRO_FOOD", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["Artisans & Handicrafts", "Food Retail", "Small Manufacturing", "Repair & Tech Services", "Transport Vehicles", "Textiles"],
    businessStages: ["IDEATION", "EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["FINANCE_LOAN", "WORKING_CAPITAL", "MACHINERY", "COLLATERAL_FREE"],
    benefits: [
      "Shishu Category: Loans up to ₹50,000 for nascent and micro-vendors",
      "Kishore Category: Loans from ₹50,000 to ₹5 Lakhs for developing enterprises",
      "Tarun & Tarun Plus Category: Loans from ₹5 Lakhs up to ₹20 Lakhs for established enterprises",
      "Strictly 100% Collateral-Free & third-party guarantee free",
      "MUDRA Card facility with pre-approved working capital limit"
    ],
    documents: [
      "Identity Proof (Aadhaar / Voter ID / Driving License)",
      "Residence Proof (Utility Bill / Ration Card / Aadhaar)",
      "Proof of Business Registration / Udyam Registration (for Kishore/Tarun)",
      "Supplier Quotations for machinery / items to be purchased",
      "Bank Account Statement for the last 6 months (existing accounts)",
      "Estimated balance sheet & income projection for Tarun category"
    ],
    applicationUrl: "https://www.udyamimitra.in/",
    officialWebsite: "https://www.mudra.org.in/",
    deadline: "Ongoing All Year",
    applicationMode: "Apply online at UdyamiMitra or walk into any Commercial/RRB/Cooperative bank",
    isActive: true,
    isPopular: true,
    badge: "100% Collateral Free"
  },
  {
    id: "scheme-cgtmse-004",
    name: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
    shortName: "CGTMSE Scheme",
    department: "Ministry of MSME & SIDBI",
    nodalAgency: "CGTMSE Trust",
    schemeType: "CREDIT_GUARANTEE",
    typeLabel: "Credit Guarantee Cover",
    description: "Enables collateral-free credit from member lending institutions up to ₹5 Crore for new and existing micro and small enterprises, with enhanced 85% guarantee coverage and reduced fees for Women and SC/ST entrepreneurs.",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 250000000,
    maxProjectCost: 50000000, // 5 Crore
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "GENERAL", "EWS", "PWD"],
    targetCategories: ["SC", "ST", "WOMEN", "PWD"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "AGRO_FOOD", "GREEN_TECH"],
    eligibleIndustries: ["Manufacturing", "IT & Software", "Healthcare", "Engineering", "Renewables", "Services"],
    businessStages: ["EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["COLLATERAL_FREE", "FINANCE_LOAN", "WORKING_CAPITAL"],
    benefits: [
      "Credit guarantee up to 85% for SC/ST and Women-led enterprises (vs 75% for general)",
      "Guarantee coverage available for credit facilities up to ₹500 Lakhs (₹5 Crore)",
      "Zero collateral or third-party guarantee required by banks",
      "Concession of 10% on annual guarantee fees for women, SC/ST, and aspirational district units",
      "Enables high-growth scaling without immovable property mortgage"
    ],
    documents: [
      "Udyam Registration Certificate",
      "Detailed Project Report (DPR) / Audited Financials (for existing)",
      "KYC documents of Promoters (Aadhaar, PAN)",
      "Bank Loan Sanction Application Form",
      "ITR for past 2 years (if existing unit)"
    ],
    applicationUrl: "https://www.cgtmse.in/",
    officialWebsite: "https://www.cgtmse.in/",
    deadline: "Ongoing",
    applicationMode: "Requested directly through your lending bank while sanctioning the business loan",
    isActive: true,
    isPopular: false,
    badge: "High-Value Guarantee"
  },
  {
    id: "scheme-svanidhi-005",
    name: "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
    shortName: "PM SVANidhi",
    department: "Ministry of Housing and Urban Affairs (MoHUA)",
    nodalAgency: "Small Industries Development Bank of India (SIDBI)",
    schemeType: "MICRO_CREDIT",
    typeLabel: "Working Capital Micro-Credit with Interest Subsidy",
    description: "Special micro-credit facility providing affordable working capital loans up to ₹50,000 with 7% interest subsidy and cashback on digital transactions to urban and peri-urban street vendors and micro-traders.",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 1000000,
    maxProjectCost: 50000,
    subsidyPercentSpecial: 7, // 7% interest subsidy
    subsidyPercentGeneral: 7,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "GENERAL", "EWS", "PWD"],
    targetCategories: ["STREET_VENDOR", "OBC", "SC", "WOMEN"],
    eligibleBusinessTypes: ["TRADING", "SERVICES", "HANDICRAFT_TEXTILE", "AGRO_FOOD"],
    eligibleIndustries: ["Street Vending", "Fruit & Veg Stalls", "Tea & Snacks Stalls", "Artisan Stalls", "Barber & Cobbler Services"],
    businessStages: ["EARLY_STAGE", "GROWTH"],
    supportTypes: ["WORKING_CAPITAL", "FINANCE_LOAN", "COLLATERAL_FREE"],
    benefits: [
      "Initial working capital loan of ₹10,000 (Tranche 1), graduated to ₹20,000 (Tranche 2) and ₹50,000 (Tranche 3)",
      "7% interest subsidy credited directly to bank account on timely repayment",
      "Cashback incentives up to ₹1,200 per year for adopting digital transactions (UPI/QR)",
      "Zero penalty on early pre-closure",
      "Builds formal credit history for marginalized micro-entrepreneurs"
    ],
    documents: [
      "Aadhaar Card linked with active mobile number",
      "Vending Certificate / Identity Card issued by Urban Local Body (ULB) / Letter of Recommendation (LoR)",
      "Active Bank Account Passbook / Statement",
      "UPI ID / QR Code (for digital transaction cashback)"
    ],
    applicationUrl: "https://pmsvanidhi.mohua.gov.in/",
    officialWebsite: "https://pmsvanidhi.mohua.gov.in/",
    deadline: "Ongoing Scheme",
    applicationMode: "Online through PM SVANidhi Portal or Common Service Centres (CSC)",
    isActive: true,
    isPopular: true,
    badge: "Micro Vendors & Artisans"
  },
  {
    id: "scheme-vcfsc-006",
    name: "Venture Capital Fund for Scheduled Castes (VCF-SC)",
    shortName: "VCF-SC",
    department: "Ministry of Social Justice and Empowerment",
    nodalAgency: "IFCI Venture Capital Funds Ltd",
    schemeType: "VENTURE_CAPITAL",
    typeLabel: "Equity & Quasi-Equity Capital",
    description: "First-of-its-kind venture fund in India providing concessional financial assistance in the form of equity/debt to innovative projects and scalable business units promoted by Scheduled Caste entrepreneurs with at least 51% SC shareholding.",
    minAge: 21,
    maxAge: 65,
    minTurnover: 0,
    maxTurnover: 200000000,
    maxProjectCost: 150000000, // Up to 15 Crore
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC"],
    targetCategories: ["SC"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "GREEN_TECH", "AGRO_FOOD"],
    eligibleIndustries: ["Technology", "Precision Manufacturing", "Renewable Energy", "Waste Management", "Healthcare", "Food Tech"],
    businessStages: ["EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["FINANCE_LOAN", "TECH_ADOPTION", "EXPORT", "BUSINESS_GROWTH"],
    benefits: [
      "Financial assistance between ₹20 Lakhs and ₹15 Crore per SC enterprise",
      "Offered as Equity, Compulsorily Convertible Debentures (CCDs), or concessional debt",
      "Low interest rate (approx 4% for SC women/disabled, 8% general SC) on debt component",
      "Tenure up to 8-10 years with comfortable exit routes",
      "Mentorship and advisory support from top industry specialists"
    ],
    documents: [
      "SC Caste Certificate issued by competent district revenue authority",
      "Company Registration (Pvt Ltd / LLP) showing 51%+ SC shareholding for at least 12 months",
      "Detailed Business Plan & Pitch Deck",
      "Audited Financial Statements / Projected Balance Sheets",
      "Udyam Registration & Tax Returns (PAN, GST)"
    ],
    applicationUrl: "https://www.vcfsc.in/",
    officialWebsite: "https://www.vcfsc.in/",
    deadline: "Open round the year",
    applicationMode: "Direct application through IFCI Venture Capital Portal",
    isActive: true,
    isPopular: false,
    badge: "SC High-Growth & Equity"
  },
  {
    id: "scheme-pmfme-007",
    name: "PM Formalisation of Micro food processing Enterprises (PMFME)",
    shortName: "PMFME Scheme",
    department: "Ministry of Food Processing Industries (MoFPI)",
    nodalAgency: "National Institute of Food Technology Entrepreneurship and Management (NIFTEM)",
    schemeType: "CAPITAL_SUBSIDY",
    typeLabel: "Credit Linked Capital Subsidy (35%)",
    description: "Centrally sponsored scheme providing 35% credit-linked capital subsidy up to ₹10 Lakhs for individual micro food processing units, Self Help Groups (SHGs), and Farmer Producer Organizations (FPOs), with special focus on One District One Product (ODOP).",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 30000000,
    maxProjectCost: 3000000,
    subsidyPercentSpecial: 35,
    subsidyPercentGeneral: 35,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "GENERAL", "EWS", "PWD"],
    targetCategories: ["WOMEN", "OBC", "SC", "ST", "SHG_MEMBER"],
    eligibleBusinessTypes: ["AGRO_FOOD", "MANUFACTURING"],
    eligibleIndustries: ["Food Processing", "Spices & Condiments", "Bakery & Confectionery", "Dairy & Pickles", "Millet Products", "Oil Extraction"],
    businessStages: ["IDEATION", "EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["CAPITAL_SUBSIDY", "MACHINERY", "MARKETING_EXHIBITION", "SKILL_TRAINING"],
    benefits: [
      "Credit-linked capital subsidy of 35% of eligible project cost with a ceiling of ₹10 Lakh per unit",
      "Seed capital of ₹40,000 per SHG member for working capital and small tool purchases",
      "Up to 50% grant for Common Infrastructure, Branding, and Marketing support",
      "Comprehensive free technical training on food safety standards (FSSAI) and packaging",
      "Priority assistance for One District One Product (ODOP) aligned clusters"
    ],
    documents: [
      "Aadhaar and PAN Card of Entrepreneur / SHG Leader",
      "Proof of Food Processing Experience or Ownership of Existing Unit",
      "FSSAI License / Registration (or application acknowledgement)",
      "Detailed Project Report for Machinery Upgradation",
      "Quotation for Food Processing Machinery",
      "Bank Account Statements"
    ],
    applicationUrl: "https://pmfme.mofpi.gov.in/",
    officialWebsite: "https://pmfme.mofpi.gov.in/",
    deadline: "Active under Atmanirbhar Bharat Abhiyan",
    applicationMode: "Online via PMFME National MIS Portal assisted by District Resource Persons (DRP)",
    isActive: true,
    isPopular: true,
    badge: "Food & Agro Processing"
  },
  {
    id: "scheme-nssh-008",
    name: "National SC-ST Hub (NSSH)",
    shortName: "National SC-ST Hub",
    department: "Ministry of MSME",
    nodalAgency: "National Small Industries Corporation (NSIC)",
    schemeType: "MARKET_ACCESS_SUBSIDY",
    typeLabel: "Public Procurement & Capacity Building Subsidy",
    description: "Empowers SC and ST entrepreneurs to participate effectively in the Government Public Procurement Policy (4% mandatory CPSE procurement quota) by providing up to 85% subsidies on stall rentals, tech acquisition, and quality certifications.",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 100000000,
    maxProjectCost: 2500000,
    subsidyPercentSpecial: 85,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST"],
    targetCategories: ["SC", "ST"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "TRADING", "AGRO_FOOD", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["All MSME Industries", "Manufacturing", "Electricals", "Garments", "Software & IT"],
    businessStages: ["EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["MARKETING_EXHIBITION", "TECH_ADOPTION", "SKILL_TRAINING", "EXPORT"],
    benefits: [
      "100% reimbursement of stall rent (up to ₹3 Lakhs) for participating in domestic trade fairs/exhibitions",
      "Reimbursement of 80% or up to ₹1 Lakh for obtaining ISO, BIS, ZED, and quality certifications",
      "Special subsidy on GeM (Government e-Marketplace) registration and digital onboarding",
      "Direct tender vendor development meets with Central Public Sector Enterprises (CPSEs)",
      "Free entrepreneurship skill and managerial capacity training"
    ],
    documents: [
      "Valid Caste Certificate of SC/ST Category",
      "Udyam Registration Certificate with SC/ST classification verified",
      "Proof of 51%+ SC/ST Shareholding in enterprise",
      "Invoice and receipts for trade fair stalls / certification expenses",
      "Bank Account details for Direct Benefit Transfer (DBT)"
    ],
    applicationUrl: "https://www.scsthub.in/",
    officialWebsite: "https://www.scsthub.in/",
    deadline: "Ongoing Scheme",
    applicationMode: "Online through NSSH Portal or through 15+ NSIC Zonal Hub Offices",
    isActive: true,
    isPopular: false,
    badge: "SC/ST Market & GeM Subsidy"
  },
  {
    id: "scheme-nbcfdc-009",
    name: "NBCFDC Term Loan & Micro Finance Schemes",
    shortName: "NBCFDC OBC Support",
    department: "Ministry of Social Justice and Empowerment",
    nodalAgency: "National Backward Classes Finance and Development Corporation (NBCFDC)",
    schemeType: "CONCESSIONAL_LOAN",
    typeLabel: "Concessional Term Loan (3% to 6% Interest)",
    description: "Provides highly subsidized concessional term loans and micro-finance up to ₹15 Lakhs for Other Backward Classes (OBC) entrepreneurs with annual family income up to ₹3 Lakhs to set up self-employment ventures.",
    minAge: 18,
    maxAge: 60,
    minTurnover: 0,
    maxTurnover: 5000000,
    maxProjectCost: 1500000,
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["OBC"],
    targetCategories: ["OBC"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "TRADING", "AGRO_FOOD", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["Artisan Crafts", "Retail Trading", "Transport & Mechanics", "Agriculture & Allied", "Small Workshops"],
    businessStages: ["IDEATION", "EARLY_STAGE", "GROWTH"],
    supportTypes: ["FINANCE_LOAN", "WORKING_CAPITAL", "MACHINERY", "COLLATERAL_FREE"],
    benefits: [
      "Low concessional interest rates between 3% to 6% per annum for OBC beneficiaries",
      "Financial assistance up to ₹15 Lakhs for individual units; up to ₹50,000 per SHG member",
      "Funding covers up to 85% to 90% of total project cost",
      "Repayment tenure of up to 5 to 7 years with initial grace period",
      "Special Mahila Samriddhi component for backward class women at 4% interest rate"
    ],
    documents: [
      "OBC Caste Certificate issued by Revenue Authority",
      "Income Certificate showing annual family income under ₹3.00 Lakhs",
      "Aadhaar Card and Residential Address Proof",
      "Business Project Estimation / Quotation",
      "Bank Account Details"
    ],
    applicationUrl: "https://nbcfdc.gov.in/",
    officialWebsite: "https://nbcfdc.gov.in/",
    deadline: "Rolling State Allocations",
    applicationMode: "Apply via State Channelising Agencies (SCAs) or Regional Rural Banks",
    isActive: true,
    isPopular: false,
    badge: "Low 3-6% Interest for OBC"
  },
  {
    id: "scheme-tpride-010",
    name: "T-PRIDE (Telangana Program for Rapid Incubation of Dalit Entrepreneurs)",
    shortName: "T-PRIDE Telangana",
    department: "Industries & Commerce Department, Government of Telangana",
    nodalAgency: "Commissioner of Industries, Telangana",
    schemeType: "STATE_SPECIAL_INCENTIVE",
    typeLabel: "State Capital Investment Subsidy (35% to 45%)",
    description: "State government flagship scheme tailored specifically for SC and ST entrepreneurs in Telangana, offering up to 45% investment subsidy on fixed capital investment, 100% stamp duty reimbursement, and 9% power tariff rebate.",
    minAge: 18,
    maxAge: 65,
    minTurnover: 0,
    maxTurnover: 100000000,
    maxProjectCost: 20000000,
    subsidyPercentSpecial: 45, // 35% for general SC/ST, up to 45% for women SC/ST
    subsidyPercentGeneral: 0,
    states: ["Telangana", "ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "PWD"],
    targetCategories: ["SC", "ST", "WOMEN"],
    eligibleBusinessTypes: ["MANUFACTURING", "SERVICES", "AGRO_FOOD", "GREEN_TECH", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["Automotive & Commercial Vehicles", "Plastic & Polymer", "Textiles", "Food Processing", "Electronics", "Service Units"],
    businessStages: ["EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["CAPITAL_SUBSIDY", "MACHINERY", "INFRASTRUCTURE", "FINANCE_LOAN"],
    benefits: [
      "35% Investment Subsidy on Fixed Capital Investment (FCI), enhanced to 45% (up to ₹75 Lakhs) for SC/ST Women",
      "100% Reimbursement of Stamp Duty, Transfer Duty, and Land Conversion Charges",
      "Power tariff subsidy of ₹1.50 per unit for 5 years from date of commercial production",
      "Reimbursement of 100% Net SGST for micro/small enterprises for 5 years",
      "Special transport sector driver-to-owner vehicle ownership subsidy"
    ],
    documents: [
      "Caste Certificate (SC/ST) from Telangana MeeSeva authority",
      "TS-iPASS Industrial Building/Operation Approval",
      "Udyam Registration Certificate in Telangana",
      "Proof of Land / Factory Shed Allotment / Lease Agreement",
      "Detailed Chartered Engineer Approved Valuation of Plant & Machinery",
      "Bank Loan Sanction and Release Letters"
    ],
    applicationUrl: "https://ipass.telangana.gov.in/",
    officialWebsite: "https://industries.telangana.gov.in/",
    deadline: "Ongoing State Policy",
    applicationMode: "Online via TS-iPASS Single Window Portal",
    isActive: true,
    isPopular: true,
    badge: "Telangana SC/ST Special"
  },
  {
    id: "scheme-msmechampions-011",
    name: "MSME Champions Scheme (ZED & Digital MSME)",
    shortName: "MSME Champions",
    department: "Ministry of Micro, Small and Medium Enterprises",
    nodalAgency: "Office of Development Commissioner (MSME)",
    schemeType: "QUALITY_TECH_SUBSIDY",
    typeLabel: "Zero Defect Zero Effect (ZED) & Tech Grant",
    description: "Financial assistance up to 85% for MSMEs to adopt Zero Defect Zero Effect (ZED) manufacturing practices, energy-efficient tech, digital automation, and clean tech, with extra 10% subsidy for Women and SC/ST owned units.",
    minAge: 18,
    maxAge: 70,
    minTurnover: 0,
    maxTurnover: 500000000,
    maxProjectCost: 1000000,
    subsidyPercentSpecial: 85, // 85% for Micro SC/ST/Women
    subsidyPercentGeneral: 75,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "OBC", "WOMEN", "MINORITY", "GENERAL", "EWS", "PWD"],
    targetCategories: ["WOMEN", "SC", "ST", "OBC"],
    eligibleBusinessTypes: ["MANUFACTURING", "AGRO_FOOD", "GREEN_TECH", "HANDICRAFT_TEXTILE"],
    eligibleIndustries: ["Manufacturing", "Engineering", "Apparel", "Precision Tools", "Food Processing"],
    businessStages: ["EARLY_STAGE", "GROWTH", "EXPANSION"],
    supportTypes: ["TECH_ADOPTION", "SKILL_TRAINING", "EXPORT", "MACHINERY"],
    benefits: [
      "Up to 85% subsidy on ZED Bronze, Silver, and Gold quality certification costs (Bronze certification effectively free)",
      "Financial assistance up to ₹5 Lakhs for Handholding & Consulting to achieve quality standards",
      "Financial assistance up to ₹3 Lakhs for Cloud Computing and Enterprise ERP software adoption",
      "Interest subvention of 0.5% on bank loans for ZED certified units",
      "Waiver of processing fees by leading public sector banks"
    ],
    documents: [
      "Udyam Registration Certificate",
      "Factory / Workshop Electricity Bill",
      "Plant Machinery Asset List",
      "Bank Account Details",
      "Self-Assessment ZED Checklist"
    ],
    applicationUrl: "https://zed.msme.gov.in/",
    officialWebsite: "https://champions.gov.in/",
    deadline: "Ongoing MSME Scheme",
    applicationMode: "Online via MSME ZED Portal",
    isActive: true,
    isPopular: false,
    badge: "Tech & ZED Certification"
  },
  {
    id: "scheme-asiim-012",
    name: "Ambedkar Social Innovation & Incubation Mission (ASIIM)",
    shortName: "ASIIM Innovation",
    department: "Ministry of Social Justice and Empowerment",
    nodalAgency: "Venture Capital Fund for SCs (VCF-SC)",
    schemeType: "INNOVATION_GRANT",
    typeLabel: "Equity Grant for SC Youth & Tech Startups",
    description: "Provides equity funding of up to ₹30 Lakhs over 3 years to innovative tech and business startup ideas developed by SC/ST youth, student innovators, and women entrepreneurs incubated at recognized Technology Business Incubators (TBIs).",
    minAge: 18,
    maxAge: 45,
    minTurnover: 0,
    maxTurnover: 50000000,
    maxProjectCost: 3000000,
    subsidyPercentSpecial: 100,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "ST", "PWD"],
    targetCategories: ["SC", "ST", "WOMEN"],
    eligibleBusinessTypes: ["SERVICES", "MANUFACTURING", "GREEN_TECH", "AGRO_FOOD"],
    eligibleIndustries: ["AgriTech", "HealthTech", "CleanTech", "EdTech", "Hardware & IoT", "AI & Software"],
    businessStages: ["IDEATION", "EARLY_STAGE"],
    supportTypes: ["FINANCE_LOAN", "TECH_ADOPTION", "SKILL_TRAINING", "BUSINESS_GROWTH"],
    benefits: [
      "₹30 Lakhs equity/grant support spread across 3 tranches (₹10L per year) upon achieving milestones",
      "Free incubation space, laboratory access, and mentorship at premier IIT/NIT/DST-supported TBIs",
      "Direct pathway for subsequent Series-A growth equity funding up to ₹5 Crore from VCF-SC",
      "Intellectual Property (IP) and patent filing assistance subsidies",
      "National exposure through Startup India and MSME demo days"
    ],
    documents: [
      "SC/ST Caste Certificate",
      "Incubation Recommendation Letter from a recognized TBI / University Incubator",
      "Innovative Prototype Proof / Pitch Deck",
      "Company / LLP Incorporation Certificate (at least 51% SC owned)",
      "Founder Aadhaar and PAN"
    ],
    applicationUrl: "https://asiim.in/",
    officialWebsite: "https://vcfsc.in/asiim",
    deadline: "Bi-annual Cohort Cycles",
    applicationMode: "Online submission via TBIs and ASIIM Web Portal",
    isActive: true,
    isPopular: false,
    badge: "SC Youth & Tech Startups"
  },
  {
    id: "scheme-mahila-samridhi-013",
    name: "Mahila Samridhi Yojana (Micro-finance for Women)",
    shortName: "Mahila Samridhi",
    department: "Ministry of Social Justice and Empowerment",
    nodalAgency: "National Scheduled Castes Finance and Development Corporation (NSFDC)",
    schemeType: "MICRO_FINANCE",
    typeLabel: "Micro-Credit at 4% Interest for Women",
    description: "Micro-finance credit scheme for marginalized SC women entrepreneurs and Self-Help Groups (SHGs) to start or expand small home-based, artisanal, or village businesses with ultra-low 4% annual interest rate.",
    minAge: 18,
    maxAge: 65,
    minTurnover: 0,
    maxTurnover: 3000000,
    maxProjectCost: 140000,
    subsidyPercentSpecial: 0,
    subsidyPercentGeneral: 0,
    states: ["ALL_INDIA"],
    eligibleCategories: ["SC", "WOMEN"],
    targetCategories: ["WOMEN", "SC"],
    eligibleBusinessTypes: ["HANDICRAFT_TEXTILE", "TRADING", "SERVICES", "AGRO_FOOD"],
    eligibleIndustries: ["Handloom & Tailoring", "Dairy Farming", "Grocery & Petty Shops", "Clay & Pottery", "Beauty Care", "Bangle Making"],
    businessStages: ["IDEATION", "EARLY_STAGE", "GROWTH"],
    supportTypes: ["FINANCE_LOAN", "WORKING_CAPITAL", "COLLATERAL_FREE"],
    benefits: [
      "Micro-loan up to ₹1,40,000 per woman beneficiary (up to ₹28 Lakhs for SHG of 20 members)",
      "Ultra-low concessional interest rate of only 4% per annum for the woman borrower",
      "NSFDC provides 95% of the total project cost",
      "Zero collateral required; simple SHG peer-guarantee model",
      "Repayment tenure of up to 3 years in easy quarterly installments"
    ],
    documents: [
      "Aadhaar Card of Woman Entrepreneur",
      "SC Caste Certificate",
      "Income Certificate (family income below ₹3.00 Lakhs per annum)",
      "SHG Membership Proof / Passbook Copy",
      "Voter ID / Ration Card"
    ],
    applicationUrl: "https://nsfdc.nic.in/",
    officialWebsite: "https://nsfdc.nic.in/",
    deadline: "Ongoing Scheme",
    applicationMode: "Apply through State Channelising Agencies or recognized Micro-Finance Institutions",
    isActive: true,
    isPopular: true,
    badge: "4% Concessional Women Loan"
  }
];
